### ISSUE TITLE
Make this our official StaySorted.com website

### ISSUE THREAD

**Issue by leotumwattana** [leotumwattana/leotumwattana.github.io#3]
@harryworld @dexvitality
Let's use this repo as our official website: staysorted.com. 
- [x] ~~Update and push website code to this repo.~~ -> #4
- [x] Update staysorted.co to redirect to staysorted.com. (~~https://github.com/get-sorted~~) (https://github.com/StaySortedHQ/staysorted.co)
- [x] Update get-sorted.co to redirect to staysorted.com. (redirect done at namecheap.com)
- [x] Update onereminder.co to redirect to staysorted.com.

**Comment by harryworld** [comment]
Can you put down the repo for the different existing domains? @leotumwattana

**Comment by leotumwattana** [comment]
Sure. Let me do that after I move my computer stuff out of Cyberport.

**Comment by harryworld** [comment]
onereminder.co (Current repo)
Being removed as `CNAME` changed

**Comment by leotumwattana** [comment]
@harryworld 

Okay. Just got back.
- [x] staysorted.co -> ~~https://github.com/get-sorted~~ -> https://github.com/StaySortedHQ/staysorted.co
- [x] get-sorted.co -> Redirected at namecheap.com level. I've updated this to point to staysorted.com.

So only thing left is to replace github.com/get-sorted with the full website code.
